name: car_seek
description: "TFG hecho por RaÃºl SÃ¡nchez y Sergio Rasillo."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter

  provider: ^6.1.4
  get_it: ^8.0.3
  uuid: ^4.5.1
  #ProgramaciÃ³n funcional
  dartz: ^0.10.1
  # ğŸ”— ConexiÃ³n con Supabase (Base de Datos y AutenticaciÃ³n)
  supabase_flutter: ^2.8.4  # Cliente de Supabase para Flutter

  # ğŸ—ï¸ State Management
  flutter_bloc: ^8.1.3  # Usar Bloc para manejar el estado de la app

  # ğŸ” Manejo de Tokens y Seguridad
  shared_preferences: ^2.2.2  # Guardar sesiÃ³n localmente
  flutter_secure_storage: ^9.0.0  # Almacenar datos sensibles
  crypto: ^3.0.6 #Cifrar datos
  flutter_dotenv: ^5.0.2

  # ğŸ“ Mapas y UbicaciÃ³n
  google_maps_flutter: ^2.5.0  # Google Maps para mostrar vehÃ­culos
  geolocator: ^10.1.0  # Obtener ubicaciÃ³n del usuario

  # ğŸ“¦ Almacenamiento de ImÃ¡genes en Supabase
  image_picker: ^1.1.2  # Seleccionar imÃ¡genes desde galerÃ­a o cÃ¡mara
  mime: ^2.0.0
  dio: ^5.4.1  # Manejar peticiones HTTP para subir imÃ¡genes

  # ğŸ“© Chat en tiempo real (Usando Supabase Realtime)

  # ğŸ’³ Pagos en la app
  flutter_stripe: ^9.4.0  # Integrar pagos con Stripe

  # ğŸ¨ UI y Animaciones
  lottie: ^2.7.0  # Animaciones
  cached_network_image: ^3.3.1  # Cargar imÃ¡genes con cachÃ©

  # ğŸ Debugging
  fluttertoast: ^8.2.5  # Mostrar mensajes en pantalla

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - .env
    - assets/images/CarSeekSinFondo.png
    - assets/images/VentaVehiculo.png